//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int emp_id { get; set; }
        public string emp_code { get; set; }
        public string emp_name { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public Nullable<System.DateTime> date_of_joining { get; set; }
        public string department { get; set; }
        public string report_to { get; set; }
        public string contact_number { get; set; }
        public Nullable<bool> resigned { get; set; }
        public Nullable<System.DateTime> resigned_date { get; set; }
    }
}
